/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numberguessguilab;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Mark
 */
public class NumberGuessGui extends javax.swing.JFrame {
    
    private int guess =0;
    private NumberGuessService go;
    private String wrong;
    /**
     * Creates new form NumberGuessGui
     */
    public NumberGuessGui() {
        initComponents();
        this.startNewGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuess = new javax.swing.JButton();
        txtGuessTxt = new javax.swing.JTextField();
        lblRange = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblWrongGuess = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuess.setText("Guess...");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        txtGuessTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRange.setText("jLabel1");

        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblWrongGuess.setForeground(new java.awt.Color(153, 0, 0));

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(txtGuessTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWrongGuess))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnQuit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuess)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewGame)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblRange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGuessTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuess)
                    .addComponent(btnQuit)
                    .addComponent(btnNewGame))
                .addGap(49, 49, 49)
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(lblWrongGuess)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void startNewGame(){
        go = new NumberGuessService(new NumberGuessResult());
        int num1=0,num2=1;
        try{
         num1 = Integer.parseInt(JOptionPane.showInputDialog(null, "Insert a number"));
        }catch (NumberFormatException nfe){
          num1 = Integer.parseInt(JOptionPane.showInputDialog(null, "Insert a number. USE ONLY WHOLE NUMBERS"));  
        }
        try{
         num2 = Integer.parseInt(JOptionPane.showInputDialog(null, "Insert a number"));
        }catch (NumberFormatException nfe){
            num2 = Integer.parseInt(JOptionPane.showInputDialog(null, "Insert a number. USE ONLY WHOLE NUMBERS"));
        }
        go.setNums(num1, num2);
        
        wrong=("Wrong Guesses: "); 
        this.lblWrongGuess.setText(wrong);
        this.lblRange.setForeground(Color.ORANGE);
        this.lblRange.setText("Guess a number between "+go.getNgr().getLowEnd()+" & "+go.getNgr().getHighEnd());
        
    }
    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        wrong=("Wrong Guesses: ");
        try{
         guess = Integer.parseInt(this.txtGuessTxt.getText());
         this.lblResult.setText(go.getNgr().compare(guess));
        this.lblResult.setForeground(go.getNgr().getMsgColor()); 
         
        }catch (NumberFormatException nfe){
            this.lblResult.setForeground(Color.RED);
            lblResult.setText("Please Only Enter Numbers");
        }
        
        for(int i=0;i<=go.getNgr().getGuesses().size()-1;i++){
            this.wrong+=(go.getNgr().getGuesses().get(i))+(", ");
               
        }
        this.lblWrongGuess.setText(wrong);
    }//GEN-LAST:event_btnGuessActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        this.dispose();
        this.startNewGame();
        this.setVisible(true);
    }//GEN-LAST:event_btnNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblWrongGuess;
    private javax.swing.JTextField txtGuessTxt;
    // End of variables declaration//GEN-END:variables
}
